import { Streamer } from 'src/features/feed';

export const streamerData: Streamer[] = [
  {
    id: 'e1',
    name: 'BrendenLive',
    icon: 'https://randomuser.me/api/portraits/men/1.jpg',
    following: true,
    subscribed: true,
    online: true,
  },
  {
    id: 'e2',
    name: 'DaisyTTV',
    icon: 'https://randomuser.me/api/portraits/women/44.jpg',
    following: true,
    subscribed: false,
    online: true,
  },
  {
    id: 'e3',
    name: 'JamesLion',
    icon: 'https://randomuser.me/api/portraits/men/3.jpg',
    following: false,
    subscribed: true,
    online: false,
  },
  {
    id: 'e4',
    name: 'BrandenDunn',
    icon: 'https://randomuser.me/api/portraits/men/4.jpg',
    following: true,
    subscribed: true,
    online: true,
  },
  {
    id: 'e5',
    name: 'SnailSong',
    icon: 'https://randomuser.me/api/portraits/women/45.jpg',
    following: true,
    subscribed: false,
    online: true,
  },
  {
    id: 'e6',
    name: 'GaryJam',
    icon: 'https://randomuser.me/api/portraits/men/8.jpg',
    following: true,
    subscribed: true,
    online: true,
  },
  {
    id: 'e7',
    name: 'sharepickaxe',
    icon: 'https://randomuser.me/api/portraits/men/18.jpg',
    following: true,
    subscribed: false,
    online: true,
  },
  {
    id: 'e8',
    name: 'Redselect',
    icon: 'https://randomuser.me/api/portraits/men/10.jpg',
    following: false,
    subscribed: true,
    online: false,
  },
  {
    id: 'e9',
    name: 'BaileyB',
    icon: 'https://randomuser.me/api/portraits/women/6.jpg',
    following: true,
    subscribed: true,
    online: true,
  },
  {
    id: 'e10',
    name: 'WingTiffey',
    icon: 'https://randomuser.me/api/portraits/women/8.jpg',
    following: true,
    subscribed: false,
    online: true,
  },
];
